### ISSUE TITLE
Runtime error: Windows PDB writer is not available  -- could not find Microsoft.DiaSymReader.Native.x86.dll

### ISSUE THREAD

**Issue by sirajmansour-infotrack** [StackExchange/StackExchange.Precompilation#10]
After changing our build process to use the StackExchange precompiler, everything builds successfully and our build time has drastically improved thanks to this great compiler.

However we're seeing this runtime error on some of our environments as soon as we started using the stackexchange precompiler. Oddly enough, on the same environments we deploy the same application twice but with different configs, one works fine and the other is just broken because of this this runtime error :
`Windows PDB writer is not available  -- could not find Microsoft.DiaSymReader.Native.x86.dll`.

We generate and keep PDB files for our test and staging environments.

One theory is that one of the applications is deployed in IIS as a Website, and the other as a Web Application, but both exactly under the same privileges, Application Pool, settings, etc... But we couldn't prove this exactly either.

We're not very sure the cause behind this, in some cases re-installing visual c++ 2015 redistributable on the server fixed the issue, but in other cases it didn't.

Any help on this would be appreciated.

**Comment by m0sa** [comment]
Are you sure you're using your pre-compiled views? You shouldn't get that at runtime unless you're trying to emit a PDB stream, which would be if you're hitting the RoslynRazorViewEngine instead of the PrecompiledViewEngine.

A complete stack trace of the exception would also be very helpful.

**Comment by sirajmansour-infotrack** [comment]
Thanks for the insight, i'll look more into it and come back with more details hopefully

**Comment by DaniilSokolyuk** [comment]
Get same problem on production after 7 days of work
`System.Web.HttpParseException (0x80004005): error CS0041: Unexpected error writing debug information -- 'The version of Windows PDB writer is older than required: 'diasymreader.dll''
   at StackExchange.Precompilation.RoslynRazorViewEngine.CompileToAssembly(WebPageRazorHost host, SyntaxTree syntaxTree)
   at StackExchange.Precompilation.RoslynRazorViewEngine.GetTypeFromVirtualPathNoCache(String virtualPath)
   at StackExchange.Precompilation.RoslynRazorViewEngine.GetTypeFromVirtualPath(String virtualPath)
   at StackExchange.Precompilation.RoslynRazorViewEngine.CreateView(ControllerContext controllerContext, String viewPath, String masterPath)
   at System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache)
   at StackExchange.Profiling.Mvc.ProfilingViewEngine.<>c__DisplayClass4.<FindView>b__3()
   at StackExchange.Profiling.Mvc.ProfilingViewEngine.Find(String name, Func`1 finder, Boolean isPartial)
   at System.Web.Mvc.ViewEngineCollection.<>c__DisplayClass6.<FindView>b__5(IViewEngine e)
   at System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths)
   at System.Web.Mvc.ViewEngineCollection.Find(Func`2 cacheLocator, Func`2 locator)
   at System.Web.Mvc.ViewResult.FindView(ControllerContext context)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)

Full Trace:

RaiseOnError at offset 126 in file:line:column <filename unknown>:0:0
RecordError at offset 916 in file:line:column <filename unknown>:0:0
RecordError at offset 703 in file:line:column <filename unknown>:0:0
ResumeSteps at offset 536 in file:line:column <filename unknown>:0:0
ResumeStepsFromThreadPoolThread at offset 48 in file:line:column <filename unknown>:0:0
OnAsyncHandlerCompletion at offset 421 in file:line:column <filename unknown>:0:0
<Sync>b__3 at offset 22 in file:line:column <filename unknown>:0:0
<Sync>b__0 at offset 34 in file:line:column <filename unknown>:0:0
SafeWrapCallback at offset 113 in file:line:column <filename unknown>:0:0
QueueSynchronous at offset 169 in file:line:column <filename unknown>:0:0
Sync<T> at offset 119 in file:line:column <filename unknown>:0:0
Sync at offset 98 in file:line:column <filename unknown>:0:0
ExecuteAsynchronousCallback at offset 86 in file:line:column <filename unknown>:0:0
ExecuteAsynchronousCallback at offset 86 in file:line:column <filename unknown>:0:0
ExecuteAsynchronousCallback at offset 94 in file:line:column <filename unknown>:0:0
ExecuteAsynchronousCallback at offset 94 in file:line:column <filename unknown>:0:0
ExecuteAsynchronousCallback at offset 94 in file:line:column <filename unknown>:0:0
Execute at offset 74 in file:line:column <filename unknown>:0:0
RunInternal at offset 354 in file:line:column <filename unknown>:0:0
Run at offset 23 in file:line:column <filename unknown>:0:0
ExecuteWithThreadLocal at offset 553 in file:line:column <filename unknown>:0:0
ExecuteEntry at offset 152 in file:line:column <filename unknown>:0:0
Dispatch at offset 421 in file:line:column <filename unknown>:0:0

        `
