### ISSUE TITLE
FileLoadException when compiling

### ISSUE THREAD

**Issue by MatthewSteeples** [StackExchange/StackExchange.Precompilation#14]
Haven't verified the reason yet (although I have a theory). Getting an exception when the build task runs using the prerelease version on NuGet (appreciate it's not supported, but thought it might be useful to know):

    System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509)
    File name: 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509)
    File name: 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
       at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
       at System.Reflection.Assembly.LoadFile(String path)
       at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Lazy`1.get_Value()
       at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
    
    
       at StackExchange.Precompilation.Compilation.RunAsync()
       at StackExchange.Precompilation.CompilationProxy.RunCs(PrecompilationCommandLineArgs precompilationArgs) in C:\TeamCity\buildAgent\work\967c65bed2f567c6\StackExchange.Precompilation.Build\CompilationProxy.cs:line 78
       at StackExchange.Precompilation.CompilationProxy.RunCs(PrecompilationCommandLineArgs precompilationArgs)
       at StackExchange.Precompilation.CompilationProxy.RunCs(String[] args) in C:\TeamCity\buildAgent\work\967c65bed2f567c6\StackExchange.Precompilation.Build\CompilationProxy.cs:line 60
       at StackExchange.Precompilation.Program.Main(String[] args) in C:\TeamCity\buildAgent\work\967c65bed2f567c6\StackExchange.Precompilation.Build\Program.cs:line 15
    
I suspect it's down to the lazy loading implementation of the assembly resolver, or the fact that it's running in parallel. Looking at my command line and the references that are passed in, it is passing System.Runtime in twice. Once from the packages folder, and once from the facades folder.

.NET 4.6.2, VS 2017 latest, Windows 10

**Comment by m0sa** [comment]
It's probably the [Assembly.Load call in this line](https://github.com/StackExchange/StackExchange.Precompilation/blob/83d7071cebf595484a688d51b644fd1a817f8497/StackExchange.Precompilation.Build/CompilationAssemblyResolver.cs#L78).

Can you narrow it down to a command line call with a single .cs file and the minimal set of references (including the offending one)?

**Comment by DaniilSokolyuk** [comment]
I received a similar error on teamcity, installation .net framework 4.6.2 **SDK** helped me
